<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Make;
use Illuminate\Support\Facades\DB;

class MakeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('makes')->delete();
 $data = [
['name' => 'ACURA', 'status' => 'Active' ],
['name' => 'ALFA ROMEO', 'status' => 'Active' ],
['name' => 'AM GENERAL', 'status' => 'Active' ],
['name' => 'AMERICAN IRONHORSE', 'status' => 'Active' ],
['name' => 'APRILIA', 'status' => 'Active' ],
['name' => 'ARCTIC CAT', 'status' => 'Active' ],
['name' => 'ASTON MARTIN', 'status' => 'Active' ],
['name' => 'ATK', 'status' => 'Active' ],
['name' => 'AUDI', 'status' => 'Active' ],
['name' => 'AUTOCAR LLC.', 'status' => 'Active' ],
['name' => 'AVANTI', 'status' => 'Active' ],
['name' => 'BENTLEY', 'status' => 'Active' ],
['name' => 'BIG DOG', 'status' => 'Active' ],
['name' => 'BIMOTA', 'status' => 'Active' ],
['name' => 'BLUE BIRD', 'status' => 'Active' ],
['name' => 'BMW', 'status' => 'Active' ],
['name' => 'BOMBARDIER', 'status' => 'Active' ],
['name' => 'BUELL', 'status' => 'Active' ],
['name' => 'BUICK', 'status' => 'Active' ],
['name' => 'CADILLAC', 'status' => 'Active' ],
['name' => 'CANNONDALE', 'status' => 'Active' ],
['name' => 'CHANCE COACH TRANSIT BUS', 'status' => 'Active' ],
['name' => 'CHEVROLET', 'status' => 'Active' ],
['name' => 'CHRYSLER', 'status' => 'Active' ],
['name' => 'COBRA', 'status' => 'Active' ],
['name' => 'DAEWOO', 'status' => 'Active' ],
['name' => 'DODGE', 'status' => 'Active' ],
['name' => 'DUCATI', 'status' => 'Active' ],
['name' => 'E-TON', 'status' => 'Active' ],
['name' => 'EL DORADO', 'status' => 'Active' ],
['name' => 'FERRARI', 'status' => 'Active' ],
['name' => 'FORD', 'status' => 'Active' ],
['name' => 'FREIGHTLINER', 'status' => 'Active' ],
['name' => 'GAS GAS', 'status' => 'Active' ],
['name' => 'GILLIG', 'status' => 'Active' ],
['name' => 'GMC', 'status' => 'Active' ],
['name' => 'HARLEY DAVIDSON', 'status' => 'Active' ],
['name' => 'HINO', 'status' => 'Active' ],
['name' => 'HM', 'status' => 'Active' ],
['name' => 'HONDA', 'status' => 'Active' ],
['name' => 'HUSABERG', 'status' => 'Active' ],
['name' => 'HUSQVARNA', 'status' => 'Active' ],
['name' => 'HYUNDAI', 'status' => 'Active' ],
['name' => 'INDIAN', 'status' => 'Active' ],
['name' => 'INFINITI', 'status' => 'Active' ],
['name' => 'INTERNATIONAL', 'status' => 'Active' ],
['name' => 'ISUZU', 'status' => 'Active' ],
['name' => 'JAGUAR', 'status' => 'Active' ],
['name' => 'JEEP', 'status' => 'Active' ],
['name' => 'KAWASAKI', 'status' => 'Active' ],
['name' => 'KENWORTH', 'status' => 'Active' ],
['name' => 'KIA', 'status' => 'Active' ],
['name' => 'KTM', 'status' =>'Active'],
['name' => 'KYMCO', 'status' => 'Active' ],
['name' => 'LAFORZA', 'status' => 'Active' ],
['name' => 'LAMBORGHINI', 'status' => 'Active' ],
['name' => 'LAND ROVER', 'status' => 'Active' ],
['name' => 'LEXUS', 'status' => 'Active' ],
['name' => 'LINCOLN', 'status' => 'Active' ],
['name' => 'LOTUS', 'status' => 'Active' ],
['name' => 'MACK', 'status' => 'Active' ],
['name' => 'MAZDA', 'status' => 'Active' ],
['name' => 'MERCEDES-BENZ', 'status' => 'Active' ],
['name' => 'MERCURY', 'status' => 'Active' ],
['name' => 'MITSUBISHI', 'status' => 'Active' ],
['name' => 'MITSUBISHI FUSO', 'status' => 'Active' ],
['name' => 'MOTO GUZZI', 'status' => 'Active' ],
['name' => 'MOTOR COACH INDUSTRIES', 'status' => 'Active' ],
['name' => 'MV AGUSTA', 'status' => 'Active' ],
['name' => 'NEW FLYER', 'status' => 'Active' ],
['name' => 'NISSAN', 'status' => 'Active' ],
['name' => 'NOVA BUS CORPORATION', 'status' => 'Active' ],
['name' => 'OLDSMOBILE', 'status' => 'Active' ],
['name' => 'ORION BUS', 'status' => 'Active' ],
['name' => 'OSHKOSH MOTOR TRUCK CO.', 'status' => 'Active' ],
['name' => 'OTTAWA', 'status' => 'Active' ],
['name' => 'PANOZ', 'status' => 'Active' ],
['name' => 'PETERBILT', 'status' => 'Active' ],
['name' => 'PEUGEOT', 'status' => 'Active' ],
['name' => 'PLYMOUTH', 'status' => 'Active' ],
['name' => 'POLARIS', 'status' => 'Active' ],
['name' => 'PONTIAC', 'status' => 'Active' ],
['name' => 'PORSCHE', 'status' => 'Active' ],
['name' => 'QVALE', 'status' => 'Active' ],
['name' => 'RENAULT', 'status' => 'Active' ],
['name' => 'ROLLS ROYCE', 'status' => 'Active' ],
['name' => 'SAAB', 'status' => 'Active' ],
['name' => 'SATURN', 'status' => 'Active' ],
['name' => 'SEA-DOO', 'status' => 'Active' ],
['name' => 'SEAT', 'status' => 'Active' ],
['name' => 'SKI-DOO', 'status' => 'Active' ],
['name' => 'STERLING', 'status' => 'Active' ],
['name' => 'STERLING TRUCK', 'status' => 'Active' ],
['name' => 'SUBARU', 'status' => 'Active' ],
['name' => 'SUZUKI', 'status' => 'Active' ],
['name' => 'TM', 'status' => 'Active' ],
['name' => 'TOYOTA', 'status' => 'Active' ],
['name' => 'TRIUMPH', 'status' => 'Active' ],
['name' => 'UD', 'status' => 'Active' ],
['name' => 'VICTORY', 'status' => 'Active' ],
['name' => 'VOLKSWAGEN', 'status' => 'Active' ],
['name' => 'VOLVO', 'status' => 'Active' ],
['name' => 'WESTERN STAR', 'status' => 'Active' ],
['name' => 'WORKHORSE', 'status' => 'Active' ],
['name' => 'YAMAHA', 'status' => 'Active' ],
['name' => 'Chevrolty', 'status' => 'Active' ],
['name' => 'Toyoto', 'status' => 'Active' ],
['name' =>'new11', 'status' => 'Active' ],
['name' => 'day iiiiiiiiii', 'status' => 'Active' ],
['name' => 'dead', 'status' => 'Active' ],
['name' => 'ACURA','status' => 'Active' ],
['name' => 'abc', 'status' => 'Active' ],
['name' => 'aaaaaaa', 'status' => 'Active' ],
['name' => 'aaa', 'status' => 'Active' ],
['name' => 'BYD', 'status' => 'Active' ],
['name' => 'Skoda', 'status' => 'Active' ],
        ];


        Make::insert($data);
    }
}
