<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\VehicleModel;
use Illuminate\Support\Facades\DB;
class VehicleModelSeeder extends Seeder
{
   
    
  
        /**
         * Run the database seeds.
         */
        public function run(): void
        {
            DB::table('vehicle_models')->delete();






     $data = [
     ['make_id' => 1,'model' =>'CL', 'status' => 'Active'],
['make_id' => 1,'model' =>'EL', 'status' => 'Active'],
['make_id' => 1,'model' =>'INTEGRA', 'status' => 'Active'],
['make_id' => 1,'model' => 'MDX', 'status' => 'Active'],
['make_id' => 1,'model' => 'NSX', 'status' => 'Active'],
['make_id' => 1,'model' => 'RL', 'status' => 'Active'],
['make_id' => 1,'model' => 'TL', 'status' => 'Active'],
['make_id' => 2,'model' => '147,', 'status' => 'Active'],
['make_id' => 2,'model' => '156', 'status' => 'Active'],
['make_id' => 3,'model' => 'HUMMER', 'status' => 'Active'],
['make_id' => 4,'model' => 'CLASSIC', 'status' => 'Active'],
['make_id' => 4,'model' => 'LEGEND', 'status' => 'Active'],
['make_id' => 4,'model' => 'OUTLAW', 'status' => 'Active'],
['make_id' => 4,'model' => 'RANGER', 'status' => 'Active'],
['make_id' => 4,'model' => 'SLAMMER', 'status' => 'Active'],
['make_id' => 4,'model' => 'TEJAS', 'status' => 'Active'],
['make_id' => 4,'model' => 'THUNDER', 'status' => 'Active'],
['make_id' => 5,'model' => 'ATLANTIC 500', 'status' => 'Active'],
['make_id' => 5,'model' => 'ETV 1000 CAPONORD', 'status' => 'Active'],
['make_id' => 5,'model' => 'MOJITO CUSTOM 50', 'status' => 'Active'],
['make_id' => 5,'model' => 'MOJITO RETRO 50', 'status' => 'Active'],
['make_id' => 5,'model' => 'PEGASO 650', 'status' => 'Active'],
['make_id' => 5,'model' => 'RALLY 50', 'status' => 'Active'],
['make_id' => 5,'model' => 'RS 125', 'status' => 'Active'],
['make_id' => 5,'model' => 'RS 250', 'status' => 'Active'],
['make_id' => 5,'model' => 'RST1000 FUTURA', 'status' => 'Active'],
['make_id' => 5,'model' => 'RSV MILLE', 'status' => 'Active'],
['make_id' => 5,'model' => 'RSV MILLE R', 'status' => 'Active'],
['make_id' => 5,'model' => 'SCARABEO 125', 'status' => 'Active'],
['make_id' => 5,'model' => 'SCARABEO 150', 'status' => 'Active'],
['make_id' => 5,'model' => 'SCARABEO 50 2T', 'status' => 'Active'],
['make_id' => 5,'model' => 'SCARABEO 50 DITECH', 'status' => 'Active'],
['make_id' => 5,'model' => 'SL1000 FALCO', 'status' => 'Active'],
['make_id' => 6,'model' => '250 2X4', 'status' => 'Active'],
['make_id' => 6,'model' => '250 4X4', 'status' => 'Active'],
['make_id' => 6,'model' => '300 2X4', 'status' => 'Active'],
['make_id' => 6,'model' => '300 4X4', 'status' => 'Active'],
['make_id' => 6,'model' => '400 2X4', 'status' => 'Active'],
['make_id' => 6,'model' => '400 4X4', 'status' => 'Active'],
['make_id' => 6,'model' => '500 4X4', 'status' => 'Active'],
['make_id' => 6,'model' => '500 4X4 AUTO', 'status' => 'Active'],
['make_id' => 6,'model' => 'BEARCAT WIDETRACK', 'status' => 'Active'],
['make_id' => 6,'model' => 'MOUNTAIN CAT 1000', 'status' => 'Active'],
['make_id' => 6,'model' => 'MOUNTAIN CAT 500 EFI', 'status' => 'Active'],
['make_id' => 6,'model' => 'MOUNTAIN CAT 600 EFI', 'status' => 'Active'],
['make_id' => 6,'model' => 'MOUNTAIN CAT 600 EFI LE', 'status' => 'Active'],
['make_id' => 6,'model' => 'MOUNTAIN CAT 600 VEV', 'status' => 'Active'],
['make_id' => 6,'model' => 'MOUNTAIN CAT 8,00', 'status' => 'Active'],
['make_id' => 6,'model' => 'MOUNTAIN CAT 8,00 LE', 'status' => 'Active'],
['make_id' => 6,'model' => 'PANTERA 1000', 'status' => 'Active'],
['make_id' => 6,'model' => 'PANTERA 58,0 EFI', 'status' => 'Active'],
['make_id' => 6,'model' => 'PANTHER 370', 'status' => 'Active'],
['make_id' => 6,'model' => 'PANTHER 440', 'status' => 'Active'],
['make_id' => 6,'model' => 'PANTHER 440 ESR', 'status' => 'Active'],
['make_id' => 6,'model' => 'PANTHER 550', 'status' => 'Active'],
['make_id' => 6,'model' => 'THUNDERCAT', 'status' => 'Active'],
['make_id' => 6,'model' => 'TRIPLE TOURING', 'status' => 'Active'],
['make_id' => 6,'model' => 'Z 120', 'status' => 'Active'],
['make_id' => 6,'model' => 'Z 120 SNO PRO', 'status' => 'Active'],
['make_id' => 6,'model' => 'Z 370', 'status' => 'Active'],
['make_id' => 6,'model' => 'Z 370 ES', 'status' => 'Active'],
['make_id' => 6,'model' => 'Z 440', 'status' => 'Active'],
['make_id' => 6,'model' => 'Z 440 ES', 'status' => 'Active'],
['make_id' => 6,'model' => 'Z 440 SNO PRO', 'status' => 'Active'],
['make_id' => 6,'model' => 'ZL 500 EFI ESR', 'status' => 'Active'],
['make_id' => 6,'model' => 'ZL 550', 'status' => 'Active'],
['make_id' => 6,'model' => 'ZL 550 ESR', 'status' => 'Active'],
['make_id' => 6,'model' => 'ZL 600 EFI', 'status' => 'Active'],
['make_id' => 6,'model' => 'ZL 600 EFI ESR', 'status' => 'Active'],
['make_id' => 6,'model' => 'ZL 8,00 ESR', 'status' => 'Active'],
['make_id' => 6,'model' => 'ZR 440 SNO PRO', 'status' => 'Active'],
['make_id' => 6,'model' => 'ZR 500', 'status' => 'Active'],
['make_id' => 6,'model' => 'ZR 500 EFI', 'status' => 'Active'],
['make_id' => 6,'model' => 'ZR 500 EFI ESR', 'status' => 'Active'],
['make_id' => 6,'model' => 'ZR 600', 'status' => 'Active'],
['make_id' => 6,'model' => 'ZR 600 EFI', 'status' => 'Active'],
['make_id' => 6,'model' => 'ZR 600 EFI LE', 'status' => 'Active'],
['make_id' => 6,'model' => 'ZR 600 VEV', 'status' => 'Active'],
['make_id' => 6,'model' => 'ZR 8,00', 'status' => 'Active'],
['make_id' => 6,'model' => 'ZR 8,00 LE', 'status' => 'Active'],
['make_id' => 6,'model' => 'ZRT 600', 'status' => 'Active'],
['make_id' => 6,'model' => 'ZRT 600 LE', 'status' => 'Active'],
['make_id' => 6,'model' => 'ZRT 8,00', 'status' => 'Active'],
['make_id' => 6,'model' => 'ZRT 8,00 LE', 'status' => 'Active'],
['make_id' => 7,'model' => 'DB7', 'status' => 'Active'],
['make_id' => 7,'model' => 'VANQUISH', 'status' => 'Active'],
['make_id' => 8,'model' => '125 CC', 'status' => 'Active'],
['make_id' => 8,'model' => '250 ENDURO', 'status' => 'Active'],
['make_id' => 8,'model' => '260 ENDURO', 'status' => 'Active'],
['make_id' => 8,'model' => '50 MX', 'status' => 'Active'],
['make_id' => 8,'model' => '600 DT', 'status' => 'Active'],
['make_id' => 8,'model' => '600 MT', 'status' => 'Active'],
['make_id' => 8,'model' => '605 ENDURO', 'status' => 'Active'],
['make_id' => 9,'model' => 'A3', 'status' => 'Active'],
['make_id' => 9,'model' => 'A4', 'status' => 'Active'],
['make_id' => 9,'model' => 'A4 QUATTRO', 'status' => 'Active'],
['make_id' => 9,'model' => 'A6', 'status' => 'Active'],
['make_id' => 9,'model' => 'A6 QUATTRO', 'status' => 'Active'],
['make_id' => 9,'model' => 'A8, QUATTRO', 'status' => 'Active'],
['make_id' => 9,'model' => 'ALLROAD QUATTRO', 'status' => 'Active'],
['make_id' => 9,'model' => 'S3', 'status' => 'Active'],
['make_id' => 9,'model' => 'S4', 'status' => 'Active'],
['make_id' => 9,'model' => 'S6', 'status' => 'Active'],
['make_id' => 9,'model' => 'S8,', 'status' => 'Active'],
['make_id' => 9,'model' => 'TT', 'status' => 'Active'],
['make_id' => 10,'model' => 'TT QUATTRO', 'status' => 'Active'],
['make_id' => 11,'model' => 'II', 'status' => 'Active'],
['make_id' => 12,'model' => 'ARNAGE', 'status' => 'Active'],
['make_id' => 12,'model' => 'AZURE', 'status' => 'Active'],
['make_id' => 12,'model' => 'CONTINENTAL', 'status' => 'Active'],
['make_id' => 13,'model' => 'BOXER', 'status' => 'Active'],
['make_id' => 13,'model' => 'BULLDOG', 'status' => 'Active'],
['make_id' => 13,'model' => 'HUSKY', 'status' => 'Active'],
['make_id' => 13,'model' => 'MASTIFF', 'status' => 'Active'],
['make_id' => 13,'model' => 'PITBULL', 'status' => 'Active'],
['make_id' => 13,'model' => 'PRO SPORT', 'status' => 'Active'],
['make_id' => 13,'model' => 'VINTAGE SPORT', 'status' => 'Active'],
['make_id' => 13,'model' => 'WOLF', 'status' => 'Active'],
['make_id' => 14,'model' => 'SB8,R', 'status' => 'Active'],
['make_id' => 15,'model' => 'ALL AMERICAN', 'status' => 'Active'],
['make_id' => 15,'model' => 'SHL TC2000', 'status' => 'Active'],
['make_id' => 15,'model' => 'TC2000', 'status' => 'Active'],
['make_id' => 15,'model' => 'WANDERLODGE', 'status' => 'Active'],
['make_id' => 16,'model' => '320I', 'status' => 'Active'],
['make_id' => 16,'model' => '323I', 'status' => 'Active'],
['make_id' => 16,'model' => '325CI', 'status' => 'Active'],
['make_id' => 16,'model' => '325I', 'status' => 'Active'],
['make_id' => 16,'model' => '325XI', 'status' => 'Active'],
['make_id' => 16,'model' => '330CI', 'status' => 'Active'],
['make_id' => 16,'model' => '330I', 'status' => 'Active'],
['make_id' => 16,'model' => '330XI', 'status' => 'Active'],
['make_id' => 16,'model' => '525I', 'status' => 'Active'],
['make_id' => 16,'model' => '530I', 'status' => 'Active'],
['make_id' => 16,'model' => '540I', 'status' => 'Active'],
['make_id' => 16,'model' => '740I', 'status' => 'Active'],
['make_id' => 16,'model' => '740IL', 'status' => 'Active'],
['make_id' => 16,'model' => '750IL', 'status' => 'Active'],
['make_id' => 16,'model' => 'F650 ENDURO', 'status' => 'Active'],
['make_id' => 16,'model' => 'F650CS', 'status' => 'Active'],
['make_id' => 16,'model' => 'F650GS', 'status' => 'Active'],
['make_id' => 16,'model' => 'F650GS ABS', 'status' => 'Active'],
['make_id' => 16,'model' => 'F650GS DAKAR', 'status' => 'Active'],
['make_id' => 16,'model' => 'K1200LT', 'status' => 'Active'],
['make_id' => 16,'model' => 'K1200LTC', 'status' => 'Active'],
['make_id' => 16,'model' => 'K1200LTI ICON', 'status' => 'Active'],
['make_id' => 16,'model' => 'K1200RS', 'status' => 'Active'],
['make_id' => 16,'model' => 'M3', 'status' => 'Active'],
['make_id' => 16,'model' => 'M5', 'status' => 'Active'],
['make_id' => 16,'model' => 'R1100RL', 'status' => 'Active'],
['make_id' => 16,'model' => 'R1100RS ABS', 'status' => 'Active'],
['make_id' => 16,'model' => 'R1100RT', 'status' => 'Active'],
['make_id' => 16,'model' => 'R1100S', 'status' => 'Active'],
['make_id' => 16,'model' => 'R1100SA', 'status' => 'Active'],
['make_id' => 16,'model' => 'R1150GS', 'status' => 'Active'],
['make_id' => 16,'model' => 'R1150R', 'status' => 'Active'],
['make_id' => 16,'model' => 'R1150RS', 'status' => 'Active'],
['make_id' => 16,'model' => 'R1150RT', 'status' => 'Active'],
['make_id' => 16,'model' => 'R1200C', 'status' => 'Active'],
['make_id' => 16,'model' => 'R1200C AVANTGARDE', 'status' => 'Active'],
['make_id' => 16,'model' => 'R1200C CLASSIC', 'status' => 'Active'],
['make_id' => 16,'model' => 'R1200C EURO', 'status' => 'Active'],
['make_id' => 16,'model' => 'R1200C INDEPENDENT', 'status' => 'Active'],
['make_id' => 16,'model' => 'R1200C MONTANA', 'status' => 'Active'],
['make_id' => 16,'model' => 'R1200C PHOENIX', 'status' => 'Active'],
['make_id' => 16,'model' => 'R1200C STILETTO', 'status' => 'Active'],
['make_id' => 16,'model' => 'R8,50R', 'status' => 'Active'],
['make_id' => 16,'model' => 'X5', 'status' => 'Active'],
['make_id' => 16,'model' => 'Z3', 'status' => 'Active'],
['make_id' => 16,'model' => 'Z8,', 'status' => 'Active'],
['make_id' => 17,'model' => 'DS650', 'status' => 'Active'],
['make_id' => 17,'model' => 'DS650 BAJA', 'status' => 'Active'],
['make_id' => 17,'model' => 'DS650 RACER', 'status' => 'Active'],
['make_id' => 17,'model' => 'TRAXTER 500 4X4 AUTO', 'status' => 'Active'],
['make_id' => 17,'model' => 'TRAXTER 500 4X4 AUTO XT', 'status' => 'Active'],
['make_id' => 17,'model' => 'TRAXTER 500 XL', 'status' => 'Active'],
['make_id' => 18,'model' => 'BLAST', 'status' => 'Active'],
['make_id' => 18,'model' => 'M2 CYCLONE', 'status' => 'Active'],
['make_id' => 18,'model' => 'S3 THUNDERBOLT', 'status' => 'Active'],
['make_id' => 18,'model' => 'S3T THUNDERBOLT', 'status' => 'Active'],
['make_id' => 18,'model' => 'X1 LIGHTNING', 'status' => 'Active'],
['make_id' => 19,'model' => 'CENTURY', 'status' => 'Active'],
['make_id' => 19,'model' => 'LESABRE', 'status' => 'Active'],
['make_id' => 19,'model' => 'PARK AVENUE', 'status' => 'Active'],
['make_id' => 19,'model' => 'REGAL', 'status' => 'Active'],
['make_id' => 20,'model' => 'CATERA', 'status' => 'Active'],
['make_id' => 20,'model' => 'DEVILLE', 'status' => 'Active'],
['make_id' => 20,'model' => 'ELDORADO', 'status' => 'Active'],
['make_id' => 20,'model' => 'SEVILLE', 'status' => 'Active'],
['make_id' => 21,'model' => 'FX400', 'status' => 'Active'],
['make_id' => 21,'model' => 'MX400', 'status' => 'Active'],
['make_id' => 22,'model' => 'CNG-28,', 'status' => 'Active'],
['make_id' => 23,'model' => 'ASTRA', 'status' => 'Active'],
['make_id' => 23,'model' => 'ASTRO', 'status' => 'Active'],
['make_id' => 23,'model' => 'B7', 'status' => 'Active'],
['make_id' => 23,'model' => 'BLAZER', 'status' => 'Active'],
['make_id' => 23,'model' => 'C3500', 'status' => 'Active'],
['make_id' => 23,'model' => 'C3500HD', 'status' => 'Active'],
['make_id' => 23,'model' => 'C6500 KODIAK', 'status' => 'Active'],
['make_id' => 23,'model' => 'C7500 KODIAK', 'status' => 'Active'],
['make_id' => 23,'model' => 'CAMARO', 'status' => 'Active'],
['make_id' => 23,'model' => 'CAVALIER', 'status' => 'Active'],
['make_id' => 23,'model' => 'CHEVY', 'status' => 'Active'],
['make_id' => 23,'model' => 'CHEVY PICKUP', 'status' => 'Active'],
['make_id' => 23,'model' => 'CORVETTE', 'status' => 'Active'],
['make_id' => 23,'model' => 'EXPRESS 1500', 'status' => 'Active'],
['make_id' => 23,'model' => 'EXPRESS 2500', 'status' => 'Active'],
['make_id' => 23,'model' => 'EXPRESS 3500', 'status' => 'Active'],
['make_id' => 23,'model' => 'G30', 'status' => 'Active'],
['make_id' => 23,'model' => 'IMPALA', 'status' => 'Active'],
['make_id' => 23,'model' => 'LUMINA', 'status' => 'Active'],
['make_id' => 23,'model' => 'LUV', 'status' => 'Active'],
['make_id' => 23,'model' => 'MALIBU', 'status' => 'Active'],
['make_id' => 23,'model' => 'METRO', 'status' => 'Active'],
['make_id' => 23,'model' => 'MONTE CARLO', 'status' => 'Active'],
['make_id' => 23,'model' => 'P30', 'status' => 'Active'],
['make_id' => 23,'model' => 'PRIZM', 'status' => 'Active'],
['make_id' => 23,'model' => 'S10', 'status' => 'Active'],
['make_id' => 23,'model' => 'SILVERADO 1500', 'status' => 'Active'],
['make_id' => 23,'model' => 'SILVERADO 1500 HD', 'status' => 'Active'],
['make_id' => 23,'model' => 'SILVERADO 2500', 'status' => 'Active'],
['make_id' => 23,'model' => 'SILVERADO 2500 HD', 'status' => 'Active'],
['make_id' => 23,'model' => 'SILVERADO 3500', 'status' => 'Active'],
['make_id' => 23,'model' => 'SONORA', 'status' => 'Active'],
['make_id' => 23,'model' => 'SUBURBAN 1500', 'status' => 'Active'],
['make_id' => 23,'model' => 'SUBURBAN 2500', 'status' => 'Active'],
['make_id' => 23,'model' => 'T6500', 'status' => 'Active'],
['make_id' => 23,'model' => 'T7500', 'status' => 'Active'],
['make_id' => 23,'model' => 'TAHOE', 'status' => 'Active'],
['make_id' => 23,'model' => 'TRACKER', 'status' => 'Active'],
['make_id' => 23,'model' => 'VENTURE', 'status' => 'Active'],
['make_id' => 23,'model' => 'W3500 TILTMASTER', 'status' => 'Active'],
['make_id' => 23,'model' => 'W4500 TILTMASTER', 'status' => 'Active'],
['make_id' => 23,'model' => 'W5500 TILTMASTER', 'status' => 'Active'],
['make_id' => 24,'model' => '300M', 'status' => 'Active'],
['make_id' => 24,'model' => 'CIRRUS', 'status' => 'Active'],
['make_id' => 24,'model' => 'CONCORDE', 'status' => 'Active'],
['make_id' => 24,'model' => 'GRAND VOYAGER', 'status' => 'Active'],
['make_id' => 24,'model' => 'INTREPID', 'status' => 'Active'],
['make_id' => 24,'model' => 'LHS', 'status' => 'Active'],
['make_id' => 24,'model' => 'NEON', 'status' => 'Active'],
['make_id' => 24,'model' => 'PROWLER', 'status' => 'Active'],
['make_id' => 24,'model' => 'PT CRUISER', 'status' => 'Active'],
['make_id' => 24,'model' => 'SEBRING', 'status' => 'Active'],
['make_id' => 24,'model' => 'TOWN &', 'status' => 'Active'],
['make_id' => 24,'model' => 'VOYAGER', 'status' => 'Active'],
['make_id' => 25,'model' => 'CM50', 'status' => 'Active'],
['make_id' => 25,'model' => 'KING', 'status' => 'Active'],
['make_id' => 26,'model' => 'LANOS', 'status' => 'Active'],
['make_id' => 26,'model' => 'LEGANZA', 'status' => 'Active'],
['make_id' => 26,'model' => 'NUBIRA', 'status' => 'Active'],

['make_id' => 28,'model' => '748,', 'status' => 'Active'],
['make_id' => 28,'model' => '748, MONOPOSTO', 'status' => 'Active'],
['make_id' => 28,'model' => '748,R', 'status' => 'Active'],
['make_id' => 28,'model' => '748,S', 'status' => 'Active'],
['make_id' => 28,'model' => '748,S MONOPOSTO', 'status' => 'Active'],
['make_id' => 28,'model' => '750 SPORT', 'status' => 'Active'],
['make_id' => 28,'model' => '900', 'status' => 'Active'],
['make_id' => 28,'model' => '996 BIPOSTO', 'status' => 'Active'],
['make_id' => 28,'model' => '996 MONOPOSTO', 'status' => 'Active'],
['make_id' => 28,'model' => '996R', 'status' => 'Active'],
['make_id' => 28,'model' => '996S', 'status' => 'Active'],
['make_id' => 28,'model' => '996S MONOPOSTO', 'status' => 'Active'],
['make_id' => 28,'model' => 'MH900E', 'status' => 'Active'],
['make_id' => 28,'model' => 'MONSTER 400', 'status' => 'Active'],
['make_id' => 28,'model' => 'MONSTER 400 METALLIC', 'status' => 'Active'],
['make_id' => 28,'model' => 'MONSTER 600 DARK', 'status' => 'Active'],
['make_id' => 28,'model' => 'MONSTER 750', 'status' => 'Active'],
['make_id' => 28,'model' => 'MONSTER 750 DARK', 'status' => 'Active'],
['make_id' => 28,'model' => 'MONSTER 750 METALLIC', 'status' => 'Active'],
['make_id' => 28,'model' => 'MONSTER 900', 'status' => 'Active'],
['make_id' => 28,'model' => 'MONSTER 900 CROMO', 'status' => 'Active'],
['make_id' => 28,'model' => 'MONSTER 900 DARK', 'status' => 'Active'],
['make_id' => 28,'model' => 'MONSTER 900 METALLIC', 'status' => 'Active'],
['make_id' => 28,'model' => 'MONSTER 900S', 'status' => 'Active'],
['make_id' => 28,'model' => 'MONSTER S4', 'status' => 'Active'],
['make_id' => 28,'model' => 'ST2', 'status' => 'Active'],
['make_id' => 28,'model' => 'ST4', 'status' => 'Active'],
['make_id' => 29,'model' => 'AXL 50', 'status' => 'Active'],
['make_id' => 29,'model' => 'AXL 90', 'status' => 'Active'],
['make_id' => 29,'model' => 'BEAMER', 'status' => 'Active'],
['make_id' => 29,'model' => 'DXL 90', 'status' => 'Active'],
['make_id' => 29,'model' => 'LIGHTNING 50', 'status' => 'Active'],
['make_id' => 29,'model' => 'SIERRA 90', 'status' => 'Active'],
['make_id' => 29,'model' => 'TXL 50', 'status' => 'Active'],
['make_id' => 29,'model' => 'TXL 90', 'status' => 'Active'],
['make_id' => 29,'model' => 'YUKON', 'status' => 'Active'],
['make_id' => 29,'model' => 'YXL 150', 'status' => 'Active'],
['make_id' => 30, 'E-Z RIDER', 'status' => 'Active'],
['make_id' => 30, 'TRANSMARK RE', 'status' => 'Active'],
['make_id' => 31,'model' => '360', 'status' => 'Active'],
['make_id' => 31,'model' => '456 M', 'status' => 'Active'],
['make_id' => 31,'model' => '550 MARANELLO', 'status' => 'Active'],
['make_id' => 32,'model' => 'COURIER', 'status' => 'Active'],
['make_id' => 32,'model' => 'CROWN VICTORIA', 'status' => 'Active'],
['make_id' => 32,'model' => 'E SUPER DUTY', 'status' => 'Active'],
['make_id' => 32,'model' => 'E-150 ECONOLINE', 'status' => 'Active'],
['make_id' => 32,'model' => 'E-150 ECONOLINE CLUB WAGON', 'status' => 'Active'],
['make_id' => 32,'model' => 'E-250 ECONOLINE', 'status' => 'Active'],
['make_id' => 32,'model' => 'E-350 ECONOLINE', 'status' => 'Active'],
['make_id' => 32,'model' => 'E-350 ECONOLINE CLUB WAGON', 'status' => 'Active'],
['make_id' => 32,'model' => 'E-450 ECONOLINE SUPER DUTY', 'status' => 'Active'],
['make_id' => 32,'model' => 'E-450 ECONOLINE SUPER DUTY S', 'status' => 'Active'],
['make_id' => 32,'model' => 'E-450 ECONOLINE SUPER DUTY STRIPPED', 'status' => 'Active'],
['make_id' => 32,'model' => 'ECONOLINE', 'status' => 'Active'],
['make_id' => 32,'model' => 'ESCAPE', 'status' => 'Active'],
['make_id' => 32,'model' => 'ESCORT', 'status' => 'Active'],
['make_id' => 32,'model' => 'EXCURSION', 'status' => 'Active'],
['make_id' => 32,'model' => 'EXPEDITION', 'status' => 'Active'],
['make_id' => 32,'model' => 'EXPLORER', 'status' => 'Active'],
['make_id' => 32,'model' => 'EXPLORER SPORT TRAC', 'status' => 'Active'],
['make_id' => 32,'model' => 'F-100 RANGER', 'status' => 'Active'],
['make_id' => 32,'model' => 'F-150', 'status' => 'Active'],
['make_id' => 32,'model' => 'F-250', 'status' => 'Active'],
['make_id' => 32,'model' => 'F-250 SUPER DUTY', 'status' => 'Active'],
['make_id' => 32,'model' => 'F-350', 'status' => 'Active'],
['make_id' => 32,'model' => 'F-350 SUPER DUTY', 'status' => 'Active'],
['make_id' => 32,'model' => 'F-450', 'status' => 'Active'],
['make_id' => 32,'model' => 'F-450 SUPER DUTY', 'status' => 'Active'],
['make_id' => 32,'model' => 'F-550 SUPER DUTY', 'status' => 'Active'],
['make_id' => 32,'model' => 'F53', 'status' => 'Active'],
['make_id' => 32,'model' => 'F650', 'status' => 'Active'],
['make_id' => 32,'model' => 'F750', 'status' => 'Active'],
['make_id' => 32,'model' => 'FIESTA', 'status' => 'Active'],
['make_id' => 32,'model' => 'FOCUS', 'status' => 'Active'],
['make_id' => 32,'model' => 'GRAND MARQUIS', 'status' => 'Active'],
['make_id' => 32,'model' => 'KA', 'status' => 'Active'],
['make_id' => 32,'model' => 'LOBO', 'status' => 'Active'],
['make_id' => 32,'model' => 'MONDEO', 'status' => 'Active'],
['make_id' => 32,'model' => 'MUSTANG', 'status' => 'Active'],
['make_id' => 32,'model' => 'RANGER', 'status' => 'Active'],
['make_id' => 32,'model' => 'SABLE', 'status' => 'Active'],
['make_id' => 32,'model' => 'TAURUS', 'status' => 'Active'],
['make_id' => 32,'model' => 'WINDSTAR', 'status' => 'Active'],
['make_id' => 33,'model' => 'ARGOSY', 'status' => 'Active'],
['make_id' => 33,'model' => 'CENTURY CLASS', 'status' => 'Active'],
['make_id' => 33,'model' => 'CLASSIC', 'status' => 'Active'],
['make_id' => 33,'model' => 'CLASSIC XL', 'status' => 'Active'],
['make_id' => 33,'model' => 'COLUMBIA', 'status' => 'Active'],
['make_id' => 33,'model' => 'CONDOR', 'status' => 'Active'],
['make_id' => 33,'model' => 'CORONADO', 'status' => 'Active'],
['make_id' => 33,'model' => 'FC70', 'status' => 'Active'],
['make_id' => 33,'model' => 'FC8,0', 'status' => 'Active'],
['make_id' => 33,'model' => 'FL106', 'status' => 'Active'],
['make_id' => 33,'model' => 'FL112', 'status' => 'Active'],
['make_id' => 33,'model' => 'FL50', 'status' => 'Active'],
['make_id' => 33,'model' => 'FL60', 'status' => 'Active'],
['make_id' => 33,'model' => 'FL70', 'status' => 'Active'],
['make_id' => 33,'model' => 'FL8,0', 'status' => 'Active'],
['make_id' => 33,'model' => 'FS65', 'status' => 'Active'],
['make_id' => 33,'model' => 'MT35', 'status' => 'Active'],
['make_id' => 33,'model' => 'MT45', 'status' => 'Active'],
['make_id' => 33,'model' => 'MT55', 'status' => 'Active'],
['make_id' => 34,'model' => 'ENDUCROSS EC 200', 'status' => 'Active'],
['make_id' => 34,'model' => 'ENDUCROSS EC 250', 'status' => 'Active'],
['make_id' => 34,'model' => 'ENDUCROSS EC 300', 'status' => 'Active'],
['make_id' => 35,'model' => 'LOW FLOOR', 'status' => 'Active'],
['make_id' => 36,'model' => 'B7', 'status' => 'Active'],
['make_id' => 36,'model' => 'C3500', 'status' => 'Active'],
['make_id' => 36,'model' => 'C3500HD', 'status' => 'Active'],
['make_id' => 36,'model' => 'C6500 TOPKICK', 'status' => 'Active'],
['make_id' => 36,'model' => 'C7500 TOPKICK', 'status' => 'Active'],
['make_id' => 36,'model' => 'JIMMY', 'status' => 'Active'],
['make_id' => 36,'model' => 'SAFARI', 'status' => 'Active'],
['make_id' => 36,'model' => 'SAVANA 1500', 'status' => 'Active'],
['make_id' => 36,'model' => 'SAVANA 2500', 'status' => 'Active'],
['make_id' => 36,'model' => 'SAVANA 3500', 'status' => 'Active'],
['make_id' => 36,'model' => 'SIERRA 1500', 'status' => 'Active'],
['make_id' => 36,'model' => 'SIERRA 1500 HD', 'status' => 'Active'],
['make_id' => 36,'model' => 'SIERRA 2500', 'status' => 'Active'],
['make_id' => 36,'model' => 'SIERRA 2500 HD', 'status' => 'Active'],
['make_id' => 36,'model' => 'SIERRA 3500', 'status' => 'Active'],
['make_id' => 36,'model' => 'SIERRA C3', 'status' => 'Active'],
['make_id' => 36,'model' => 'SONOMA', 'status' => 'Active'],
['make_id' => 36,'model' => 'T6500', 'status' => 'Active'],
['make_id' => 36,'model' => 'T7500', 'status' => 'Active'],
['make_id' => 36,'model' => 'W3500 FORWARD', 'status' => 'Active'],
['make_id' => 36,'model' => 'W4500 FORWARD', 'status' => 'Active'],
['make_id' => 36,'model' => 'W5500 FORWARD', 'status' => 'Active'],
['make_id' => 36,'model' => 'YUKON', 'status' => 'Active'],
['make_id' => 36,'model' => 'YUKON XL 1500', 'status' => 'Active'],
['make_id' => 36,'model' => 'YUKON XL 2500', 'status' => 'Active'],
['make_id' => 37,'model' => 'FLHR ROAD KING', 'status' => 'Active'],
['make_id' => 37,'model' => 'FLHRCI ROAD KING CLASSIC', 'status' => 'Active'],
['make_id' => 37,'model' => 'FLHRI ROAD KING', 'status' => 'Active'],
['make_id' => 37,'model' => 'FLHT ELECTRA GLIDE STANDARD', 'status' => 'Active'],
['make_id' => 37,'model' => 'FLHTC ELECTRA GLIDE CLASSIC', 'status' => 'Active'],
['make_id' => 37,'model' => 'FLHTCI ELECTRA GLIDE CLASSIC', 'status' => 'Active'],
['make_id' => 37,'model' => 'FLHTCUI ELECTRA GLIDE ULTRA CLASSIC', 'status' => 'Active'],
['make_id' => 37,'model' => 'FLSTC HERITAGE SOFTAIL CLASSIC', 'status' => 'Active'],
['make_id' => 37,'model' => 'FLSTCI HERITAGE SOFTAIL CLASSIC', 'status' => 'Active'],
['make_id' => 37,'model' => 'FLSTF FAT BOY', 'status' => 'Active'],
['make_id' => 37,'model' => 'FLSTFI FAT BOY', 'status' => 'Active'],
['make_id' => 37,'model' => 'FLSTS HERITAGE SPRINGER', 'status' => 'Active'],
['make_id' => 37,'model' => 'FLSTSI HERITAGE SPRINGER', 'status' => 'Active'],
['make_id' => 37,'model' => 'FLTR ROAD GLIDE', 'status' => 'Active'],
['make_id' => 37,'model' => 'FLTRI ROAD GLIDE', 'status' => 'Active'],
['make_id' => 37,'model' => 'FLTRSEI2 SCREAMIN EAGLE ROAD GLIDE', 'status' => 'Active'],
['make_id' => 37,'model' => 'FXD DYNA SUPER GLIDE', 'status' => 'Active'],
['make_id' => 37,'model' => 'FXDL DYNA LOW RIDER', 'status' => 'Active'],
['make_id' => 37,'model' => 'FXDWG DYNA WIDE GLIDE', 'status' => 'Active'],
['make_id' => 37,'model' => 'FXDWG2', 'status' => 'Active'],
['make_id' => 37,'model' => 'FXDX DYNA SUPER GLIDE SPORT', 'status' => 'Active'],
['make_id' => 37,'model' => 'FXDXT DYNA SUPER GLIDE T-SPORT', 'status' => 'Active'],
['make_id' => 37,'model' => 'FXST SOFTAIL STANDARD', 'status' => 'Active'],
['make_id' => 37,'model' => 'FXSTB NIGHT TRAIN', 'status' => 'Active'],
['make_id' => 37,'model' => 'FXSTBI NIGHT TRAIN', 'status' => 'Active'],
['make_id' => 37,'model' => 'FXSTD SOFTAIL DEUCE', 'status' => 'Active'],
['make_id' => 37,'model' => 'FXSTDI SOFTAIL DEUCE', 'status' => 'Active'],
['make_id' => 37,'model' => 'FXSTI SOFTAIL STANDARD', 'status' => 'Active'],
['make_id' => 37,'model' => 'FXSTS SPRINGER SOFTAIL', 'status' => 'Active'],
['make_id' => 37,'model' => 'FXSTSI SPRINGER SOFTAIL', 'status' => 'Active'],
['make_id' => 37,'model' => 'XL1200C SPORTSTER 1200 CUSTOM', 'status' => 'Active'],
['make_id' => 37,'model' => 'XL1200S SPORTSTER 1200 SPORT', 'status' => 'Active'],
['make_id' => 37,'model' => 'XL8,8,3C SPORTSTER 8,8,3 CUSTOM', 'status' => 'Active'],
['make_id' => 37,'model' => 'XLH1200', 'status' => 'Active'],
['make_id' => 37,'model' => 'XLH8,8,3', 'status' => 'Active'],
['make_id' => 37,'model' => 'XLH8,8,3HUG SPORTSTER 8,8,3 HUGGER', 'status' => 'Active'],
['make_id' => 38,'model' => 'FA1517,', 'status' => 'Active'],
['make_id' => 38,'model' => 'FB18,17,', 'status' => 'Active'],
['make_id' => 38,'model' => 'FD2220', 'status' => 'Active'],
['make_id' => 38,'model' => 'FE2620', 'status' => 'Active'],


['make_id' => 40, 'CB7,50 NIGHTHAWK', 'status' => 'Active'],
['make_id' => 40, 'CBR1100XX SUPER BLACKBIRD', 'status' => 'Active'],
['make_id' => 40, 'CBR600F F4I', 'status' => 'Active'],
['make_id' => 40, 'CBR929RR', 'status' => 'Active'],
['make_id' => 40, 'CH8,0 ELITE', 'status' => 'Active'],
['make_id' => 40, 'CIVIC', 'status' => 'Active'],
['make_id' => 40, 'CMX250C REBEL', 'status' => 'Active'],
['make_id' => 40, 'CN250 HELIX', 'status' => 'Active'],
['make_id' => 40, 'CR-V', 'status' => 'Active'],
['make_id' => 40, 'CR125R', 'status' => 'Active'],
['make_id' => 40, 'CR250R', 'status' => 'Active'],
['make_id' => 40, 'CR500R', 'status' => 'Active'],
['make_id' => 40, 'CR8,0R', 'status' => 'Active'],
['make_id' => 40, 'CR8,0RB EXPERT', 'status' => 'Active'],
['make_id' => 40, 'GL1500C/CD VALKYRIE', 'status' => 'Active'],
['make_id' => 40, 'GL1500CF VALKYRIE INTERSTATE', 'status' => 'Active'],
['make_id' => 40, 'GL18,00 GOLD WING', 'status' => 'Active'],
['make_id' => 40, 'GL18,00A GOLD WING ABS', 'status' => 'Active'],
['make_id' => 40, 'INSIGHT', 'status' => 'Active'],
['make_id' => 40, 'NSS 250 JAZZ', 'status' => 'Active'],
['make_id' => 40, 'NSS250 REFLEX', 'status' => 'Active'],
['make_id' => 40, 'NSS250A REFLEX ABS', 'status' => 'Active'],
['make_id' => 40, 'ODYSSEY', 'status' => 'Active'],
['make_id' => 40, 'PASSPORT', 'status' => 'Active'],
['make_id' => 40, 'PRELUDE', 'status' => 'Active'],
['make_id' => 40, 'RVT1000R RC51', 'status' => 'Active'],
['make_id' => 40, 'S2000', 'status' => 'Active'],
['make_id' => 40, 'SA50 ELITE SR', 'status' => 'Active'],
['make_id' => 40, 'SA50P ELITE S', 'status' => 'Active'],
['make_id' => 40, 'ST1100', 'status' => 'Active'],
['make_id' => 40, 'ST1100 ABS', 'status' => 'Active'],
['make_id' => 40, 'TRX250EX SPORTRAX', 'status' => 'Active'],
['make_id' => 40, 'TRX250TM FOURTRAX RECON', 'status' => 'Active'],
['make_id' => 40, 'TRX300EX SPORTRAX', 'status' => 'Active'],
['make_id' => 40, 'TRX350FE FOURTRAX RANCHER 4X4 ES', 'status' => 'Active'],
['make_id' => 40, 'TRX350FM FOURTRAX RANCHER 4X4', 'status' => 'Active'],
['make_id' => 40, 'TRX350TE FOURTRAX RANCHER ES', 'status' => 'Active'],
['make_id' => 40, 'TRX350TM FOURTRAX RANCHER', 'status' => 'Active'],
['make_id' => 40, 'TRX400EX SPORTRAX', 'status' => 'Active'],
['make_id' => 40, 'TRX400FW FOREMAN 4X4', 'status' => 'Active'],
['make_id' => 40, 'TRX450FE FOURTRAX FOREMAN ES', 'status' => 'Active'],
['make_id' => 40, 'TRX450FM FOURTRAX FOREMAN S', 'status' => 'Active'],
['make_id' => 40, 'TRX500FA FOURTRAX FOREMAN RUBICON', 'status' => 'Active'],
['make_id' => 40, 'TRX90 SPORTRAX', 'status' => 'Active'],
['make_id' => 40, 'VF7,50C MAGNA', 'status' => 'Active'],
['make_id' => 40, 'VFR8,00 INTERCEPTOR', 'status' => 'Active'],
['make_id' => 40, 'VT1100C SHADOW SPIRIT', 'status' => 'Active'],
['make_id' => 40, 'VT1100C2 SHADOW SABRE', 'status' => 'Active'],
['make_id' => 40, 'VT1100C3 SHADOW AERO', 'status' => 'Active'],
['make_id' => 40, 'VT1100T SHADOW ACE TOUR', 'status' => 'Active'],
['make_id' => 40, 'VT600C SHADOW VLX', 'status' => 'Active'],
['make_id' => 40, 'VT600CD SHADOW VLX DELUXE', 'status' => 'Active'],
['make_id' => 40, 'VT7,50C/CD SHADOW ACE', 'status' => 'Active'],
['make_id' => 40, 'VT750DC SHADOW SPIRIT', 'status' => 'Active'],
['make_id' => 40, 'VTR1000 SUPER HAWK', 'status' => 'Active'],
['make_id' => 40, 'XR100R', 'status' => 'Active'],
['make_id' => 40, 'XR200R', 'status' => 'Active'],
['make_id' => 40, 'XR250R', 'status' => 'Active'],
['make_id' => 40, 'XR400R', 'status' => 'Active'],
['make_id' => 40, 'XR50R', 'status' => 'Active'],
['make_id' => 40, 'XR650L', 'status' => 'Active'],
['make_id' => 40, 'XR650R', 'status' => 'Active'],
['make_id' => 40, 'XR70R', 'status' => 'Active'],
['make_id' => 40, 'XR8,0R', 'status' => 'Active'],
['make_id' => 41,'model' => 'FC470', 'status' => 'Active'],
['make_id' => 41,'model' => 'FC550', 'status' => 'Active'],
['make_id' => 41,'model' => 'FE400E', 'status' => 'Active'],
['make_id' => 41,'model' => 'FE501E', 'status' => 'Active'],
['make_id' => 41,'model' => 'FE650E', 'status' => 'Active'],
['make_id' => 41,'model' => 'FX470E', 'status' => 'Active'],
['make_id' => 41,'model' => 'FX650E', 'status' => 'Active'],
['make_id' => 42,'model' => 'CR125', 'status' => 'Active'],
['make_id' => 42,'model' => 'CR250', 'status' => 'Active'],
['make_id' => 42,'model' => 'CR50', 'status' => 'Active'],
['make_id' => 42,'model' => 'TC610', 'status' => 'Active'],
['make_id' => 42,'model' => 'TE400', 'status' => 'Active'],
['make_id' => 42,'model' => 'TE410', 'status' => 'Active'],
['make_id' => 42,'model' => 'TE570', 'status' => 'Active'],
['make_id' => 42,'model' => 'TE610', 'status' => 'Active'],
['make_id' => 42,'model' => 'WR125', 'status' => 'Active'],
['make_id' => 42,'model' => 'WR250', 'status' => 'Active'],
['make_id' => 42,'model' => 'WR360', 'status' => 'Active'],
['make_id' => 43,'model' => 'ACCENT', 'status' => 'Active'],
['make_id' => 43,'model' => 'ELANTRA', 'status' => 'Active'],
['make_id' => 43,'model' => 'SANTA FE', 'status' => 'Active'],
['make_id' => 43,'model' => 'SONATA', 'status' => 'Active'],
['make_id' => 43,'model' => 'TIBURON', 'status' => 'Active'],
['make_id' => 43,'model' => 'XG300', 'status' => 'Active'],
['make_id' => 44,'model' => 'CHIEF', 'status' => 'Active'],
['make_id' => 44,'model' => 'SCOUT', 'status' => 'Active'],
['make_id' => 44,'model' => 'SPIRIT', 'status' => 'Active'],
['make_id' => 45,'model' => 'G20', 'status' => 'Active'],
['make_id' => 45,'model' => 'I30', 'status' => 'Active'],
['make_id' => 45,'model' => 'Q45', 'status' => 'Active'],

['make_id' => 46,'model' => '5500I', 'status' => 'Active'],
['make_id' => 46,'model' => '5600I', 'status' => 'Active'],
['make_id' => 46,'model' => '5900I SBA', 'status' => 'Active'],
['make_id' => 46,'model' => '8,100', 'status' => 'Active'],
['make_id' => 46,'model' => '9100I SBA', 'status' => 'Active'],
['make_id' => 46,'model' => '9200I SBA', 'status' => 'Active'],
['make_id' => 46,'model' => '9400I SBA', 'status' => 'Active'],
['make_id' => 46,'model' => '9900I SFA', 'status' => 'Active'],
['make_id' => 46,'model' => '9900IX SFA', 'status' => 'Active'],
['make_id' => 46,'model' => 'GENESIS RE', 'status' => 'Active'],
['make_id' => 47,'model' => 'FRR', 'status' => 'Active'],
['make_id' => 47,'model' => 'FSR', 'status' => 'Active'],
['make_id' => 47,'model' => 'FTR', 'status' => 'Active'],
['make_id' => 47,'model' => 'FVR', 'status' => 'Active'],
['make_id' => 47,'model' => 'NPR', 'status' => 'Active'],
['make_id' => 47,'model' => 'NPR-HD', 'status' => 'Active'],
['make_id' => 47,'model' => 'NQR', 'status' => 'Active'],
['make_id' => 47,'model' => 'RODEO', 'status' => 'Active'],
['make_id' => 47,'model' => 'RODEO SPORT', 'status' => 'Active'],
['make_id' => 47,'model' => 'TROOPER', 'status' => 'Active'],
['make_id' => 47,'model' => 'VEHICROSS', 'status' => 'Active'],
['make_id' => 48,'model' => 'S-TYPE', 'status' => 'Active'],
['make_id' => 48,'model' => 'VANDEN PLAS', 'status' => 'Active'],
['make_id' => 48,'model' => 'X-TYPE', 'status' => 'Active'],
['make_id' => 48,'model' => 'XJ8,', 'status' => 'Active'],
['make_id' => 48,'model' => 'XJR', 'status' => 'Active'],
['make_id' => 48,'model' => 'XK8,', 'status' => 'Active'],
['make_id' => 48,'model' => 'XKR', 'status' => 'Active'],
['make_id' => 49,'model' => 'CHEROKEE', 'status' => 'Active'],
['make_id' => 49,'model' => 'GRAND CHEROKEE', 'status' => 'Active'],
['make_id' => 49,'model' => 'TJ', 'status' => 'Active'],
['make_id' => 49,'model' => 'WRANGLER', 'status' => 'Active'],
['make_id' => 50,'model' => 'BN125 ELIMINATOR', 'status' => 'Active'],
['make_id' => 50,'model' => 'EN500C VULCAN 500 LTD', 'status' => 'Active'],
['make_id' => 50,'model' => 'EX250F NINJA 250R', 'status' => 'Active'],
['make_id' => 50,'model' => 'EX500 NINJA 500R', 'status' => 'Active'],
['make_id' => 50,'model' => 'JH1100 1100ZXI', 'status' => 'Active'],
['make_id' => 50,'model' => 'JH1100 ULTRA 130', 'status' => 'Active'],
['make_id' => 50,'model' => 'JH1200 ULTRA 150', 'status' => 'Active'],
['make_id' => 50,'model' => 'JS750 SXI PRO', 'status' => 'Active'],
['make_id' => 50,'model' => 'JT1100 1100STX D.I.', 'status' => 'Active'],
['make_id' => 50,'model' => 'JT900 900STS', 'status' => 'Active'],
['make_id' => 50,'model' => 'JT900 900STX', 'status' => 'Active'],
['make_id' => 50,'model' => 'KAF300 MULE 520', 'status' => 'Active'],
['make_id' => 50,'model' => 'KAF300 MULE 550', 'status' => 'Active'],
['make_id' => 50,'model' => 'KAF620 MULE 3000', 'status' => 'Active'],
['make_id' => 50,'model' => 'KAF620 MULE 3010 4X4', 'status' => 'Active'],
['make_id' => 50,'model' => 'KAF620 MULE 3020', 'status' => 'Active'],
['make_id' => 50,'model' => 'KAF950 MULE 2510 DIESEL', 'status' => 'Active'],
['make_id' => 50,'model' => 'KDX200', 'status' => 'Active'],
['make_id' => 50,'model' => 'KDX220R', 'status' => 'Active'],
['make_id' => 50,'model' => 'KE100', 'status' => 'Active'],
['make_id' => 50,'model' => 'KEF300 LAKOTA SPORT', 'status' => 'Active'],
['make_id' => 50,'model' => 'KL250 SUPER SHERPA', 'status' => 'Active'],
['make_id' => 50,'model' => 'KLF220 BAYOU', 'status' => 'Active'],
['make_id' => 50,'model' => 'KLF300 BAYOU 2X4', 'status' => 'Active'],
['make_id' => 50,'model' => 'KLF300 BAYOU 4X4', 'status' => 'Active'],
['make_id' => 50,'model' => 'KLR250', 'status' => 'Active'],
['make_id' => 50,'model' => 'KLR650', 'status' => 'Active'],
['make_id' => 50,'model' => 'KLX300R', 'status' => 'Active'],
['make_id' => 50,'model' => 'KSF250 MOJAVE', 'status' => 'Active'],
['make_id' => 50,'model' => 'KVF300 PRAIRIE 2X4', 'status' => 'Active'],
['make_id' => 50,'model' => 'KVF300 PRAIRIE 4X4', 'status' => 'Active'],
['make_id' => 50,'model' => 'KVF400 PRAIRIE 2X4', 'status' => 'Active'],
['make_id' => 50,'model' => 'KVF400 PRAIRIE 4X4', 'status' => 'Active'],
['make_id' => 50,'model' => 'KX100', 'status' => 'Active'],
['make_id' => 50,'model' => 'KX125', 'status' => 'Active'],
['make_id' => 50,'model' => 'KX250', 'status' => 'Active'],
['make_id' => 50,'model' => 'KX500', 'status' => 'Active'],
['make_id' => 50,'model' => 'KX60', 'status' => 'Active'],
['make_id' => 50,'model' => 'KX65', 'status' => 'Active'],
['make_id' => 50,'model' => 'KX8,5', 'status' => 'Active'],
['make_id' => 50,'model' => 'KZ1000C/P POLICE', 'status' => 'Active'],
['make_id' => 50,'model' => 'VN1500E VULCAN 1500 CLASSIC', 'status' => 'Active'],
['make_id' => 50,'model' => 'VN1500G VULCAN 1500 NOMAD', 'status' => 'Active'],
['make_id' => 50,'model' => 'VN1500J/R VULCAN 1500 DRIFTER', 'status' => 'Active'],
['make_id' => 50,'model' => 'VN1500L VULCAN NOMAD FI', 'status' => 'Active'],
['make_id' => 50,'model' => 'VN1500N VULCAN 1500 CLASSIC FI', 'status' => 'Active'],
['make_id' => 50,'model' => 'VN750A VULCAN 750', 'status' => 'Active'],
['make_id' => 50,'model' => 'VN8,00A VULCAN 8,00', 'status' => 'Active'],
['make_id' => 50,'model' => 'VN8,00B VULCAN 8,00 CLASSIC', 'status' => 'Active'],
['make_id' => 50,'model' => 'VN8,00E VULCAN 8,00 DRIFTER', 'status' => 'Active'],
['make_id' => 50,'model' => 'W650', 'status' => 'Active'],
['make_id' => 50,'model' => 'ZG1000 CONCOURS', 'status' => 'Active'],

['make_id' => 53,'model' => '200 EXC', 'status' => 'Active'],
['make_id' => 53,'model' => '200 MXC', 'status' => 'Active'],
['make_id' => 53,'model' => '250 EXC', 'status' => 'Active'],
['make_id' => 53,'model' => '250 MXC', 'status' => 'Active'],
['make_id' => 53,'model' => '250 SX', 'status' => 'Active'],
['make_id' => 53,'model' => '250 SXS', 'status' => 'Active'],
['make_id' => 53,'model' => '300 EXC', 'status' => 'Active'],
['make_id' => 53,'model' => '300 MXC', 'status' => 'Active'],
['make_id' => 53,'model' => '38,0 EXC', 'status' => 'Active'],
['make_id' => 53,'model' => '38,0 MXC', 'status' => 'Active'],
['make_id' => 53,'model' => '38,0 SX', 'status' => 'Active'],
['make_id' => 53,'model' => '400 EXC', 'status' => 'Active'],
['make_id' => 53,'model' => '400 LC4', 'status' => 'Active'],
['make_id' => 53,'model' => '400 MXC', 'status' => 'Active'],
['make_id' => 53,'model' => '400 SX', 'status' => 'Active'],
['make_id' => 53,'model' => '50 JR ADVENTURE', 'status' => 'Active'],
['make_id' => 53,'model' => '50 MINI ADVENTURE', 'status' => 'Active'],
['make_id' => 53,'model' => '50 SX PRO SR LC', 'status' => 'Active'],
['make_id' => 53,'model' => '520 EXC', 'status' => 'Active'],
['make_id' => 53,'model' => '520 MXC', 'status' => 'Active'],
['make_id' => 53,'model' => '520 SX', 'status' => 'Active'],
['make_id' => 53,'model' => '640 ADVENTURE', 'status' => 'Active'],
['make_id' => 53,'model' => '640 DUKE II', 'status' => 'Active'],
['make_id' => 53,'model' => '640 SUPERMOTO', 'status' => 'Active'],
['make_id' => 53,'model' => '660 RALLY', 'status' => 'Active'],
['make_id' => 54,'model' => 'COBRA 50', 'status' => 'Active'],
['make_id' => 54,'model' => 'PEOPLE 50', 'status' => 'Active'],
['make_id' => 54,'model' => 'ZX 50', 'status' => 'Active'],
['make_id' => 55,'model' => 'LAFORZA', 'status' => 'Active'],
['make_id' => 56,'model' => 'DIABLO', 'status' => 'Active'],
['make_id' => 56,'model' => 'MURCIELAGO', 'status' => 'Active'],
['make_id' => 57,'model' => 'DISCOVERY', 'status' => 'Active'],
['make_id' => 57,'model' => 'FREELANDER', 'status' => 'Active'],
['make_id' => 57,'model' => 'RANGE ROVER', 'status' => 'Active'],
['make_id' => 58,'model' => 'ES300', 'status' => 'Active'],
['make_id' => 58,'model' => 'GS300', 'status' => 'Active'],
['make_id' => 58,'model' => 'GS430', 'status' => 'Active'],
['make_id' => 58,'model' => 'IS300', 'status' => 'Active'],
['make_id' => 58,'model' => 'LS430', 'status' => 'Active'],
['make_id' => 58,'model' => 'LX47,0', 'status' => 'Active'],
['make_id' => 58,'model' => 'RX300', 'status' => 'Active'],
['make_id' => 59,'model' => 'CONTINENTAL', 'status' => 'Active'],
['make_id' => 59,'model' => 'LS', 'status' => 'Active'],
['make_id' => 59,'model' => 'NAVIGATOR', 'status' => 'Active'],
['make_id' => 59,'model' => 'TOWN CAR', 'status' => 'Active'],
['make_id' => 60, 'ESPRIT', 'status' => 'Active'],
['make_id' => 61,'model' => 'CH', 'status' => 'Active'],
['make_id' => 61,'model' => 'CL', 'status' => 'Active'],
['make_id' => 61,'model' => 'CS200P MID-LINER', 'status' => 'Active'],
['make_id' => 61,'model' => 'CS300P MID-LINER', 'status' => 'Active'],
['make_id' => 61,'model' => 'CV', 'status' => 'Active'],
['make_id' => 61,'model' => 'DM', 'status' => 'Active'],
['make_id' => 61,'model' => 'DMM', 'status' => 'Active'],
['make_id' => 61,'model' => 'LE', 'status' => 'Active'],
['make_id' => 61,'model' => 'MR', 'status' => 'Active'],
['make_id' => 61,'model' => 'MS200P MID-LINER', 'status' => 'Active'],
['make_id' => 61,'model' => 'MS250P MID-LINER', 'status' => 'Active'],
['make_id' => 61,'model' => 'MS300P MID-LINER', 'status' => 'Active'],
['make_id' => 61,'model' => 'RB', 'status' => 'Active'],
['make_id' => 61,'model' => 'RD', 'status' => 'Active'],
['make_id' => 62,'model' => '626', 'status' => 'Active'],
['make_id' => 62,'model' => 'B2300', 'status' => 'Active'],
['make_id' => 62,'model' => 'B2500', 'status' => 'Active'],
['make_id' => 62,'model' => 'B3000', 'status' => 'Active'],
['make_id' => 62,'model' => 'B4000', 'status' => 'Active'],
['make_id' => 62,'model' => 'MIATA', 'status' => 'Active'],
['make_id' => 62,'model' => 'MILLENIA', 'status' => 'Active'],
['make_id' => 62,'model' => 'MPV', 'status' => 'Active'],
['make_id' => 62,'model' => 'PROTEGE', 'status' => 'Active'],
['make_id' => 62,'model' => 'TRIBUTE', 'status' => 'Active'],
['make_id' => 63,'model' => 'C240', 'status' => 'Active'],
['make_id' => 63,'model' => 'C320', 'status' => 'Active'],
['make_id' => 63,'model' => 'CL500', 'status' => 'Active'],
['make_id' => 63,'model' => 'CL55 AMG', 'status' => 'Active'],

['make_id' => 66,'model' => 'FM-HR', 'status' => 'Active'],
['make_id' => 66,'model' => 'FM-MR', 'status' => 'Active'],
['make_id' => 66,'model' => 'FM-SP', 'status' => 'Active'],
['make_id' => 66,'model' => 'FM-SR', 'status' => 'Active'],
['make_id' => 67,'model' => 'CALIFORNIA EV', 'status' => 'Active'],
['make_id' => 67,'model' => 'CALIFORNIA JACKEL', 'status' => 'Active'],
['make_id' => 67,'model' => 'CALIFORNIA SPECIAL', 'status' => 'Active'],
['make_id' => 67,'model' => 'V11 SPORT', 'status' => 'Active'],
['make_id' => 67,'model' => 'V11 SPORT ROSSO MANDELLO', 'status' => 'Active'],
['make_id' => 68,'model' => '102D3', 'status' => 'Active'],
['make_id' => 68,'model' => '102DL3', 'status' => 'Active'],
['make_id' => 68,'model' => '102EL3', 'status' => 'Active'],
['make_id' => 68,'model' => 'J4500', 'status' => 'Active'],
['make_id' => 69,'model' => 'F4-S', 'status' => 'Active'],
['make_id' => 69,'model' => 'F4-S 1+1', 'status' => 'Active'],
['make_id' => 70, 'model' =>'C30LF', 'status' => 'Active'],
['make_id' => 70, 'model' =>'C40LF', 'status' => 'Active'],
['make_id' => 70, 'model' =>'D30LF', 'status' => 'Active'],
['make_id' => 70,'model' => 'D40LF', 'status' => 'Active'],
['make_id' => 70, 'model' =>'D60LF', 'status' => 'Active'],
['make_id' => 71,'model' => 'ALMERA', 'status' => 'Active'],
['make_id' => 71,'model' => 'ALTIMA', 'status' => 'Active'],
['make_id' => 71,'model' => 'ALTRA EV', 'status' => 'Active'],
['make_id' => 71,'model' => 'FRONTIER', 'status' => 'Active'],
['make_id' => 71,'model' => 'MAXIMA', 'status' => 'Active'],
['make_id' => 71,'model' => 'PATHFINDER', 'status' => 'Active'],
['make_id' => 71,'model' => 'PICKUP', 'status' => 'Active'],
['make_id' => 71,'model' => 'QUEST', 'status' => 'Active'],
['make_id' => 71,'model' => 'SENTRA', 'status' => 'Active'],
['make_id' => 71,'model' => 'TSUBAME', 'status' => 'Active'],
['make_id' => 71,'model' => 'TSURU', 'status' => 'Active'],
['make_id' => 71,'model' => 'URVAN', 'status' => 'Active'],
['make_id' => 71,'model' => 'XTERRA', 'status' => 'Active'],
['make_id' => 72,'model' => 'RTS', 'status' => 'Active'],
['make_id' => 73,'model' => 'ALERO', 'status' => 'Active'],
['make_id' => 73,'model' => 'AURORA', 'status' => 'Active'],
['make_id' => 73,'model' => 'BRAVADA', 'status' => 'Active'],
['make_id' => 73,'model' => 'INTRIGUE', 'status' => 'Active'],
['make_id' => 73,'model' => 'SILHOUETTE', 'status' => 'Active'],
['make_id' => 74,'model' => 'ORION II', 'status' => 'Active'],
['make_id' => 74,'model' => 'ORION V', 'status' => 'Active'],
['make_id' => 74,'model' => 'ORION VI', 'status' => 'Active'],
['make_id' => 75,'model' => 'H', 'status' => 'Active'],
['make_id' => 75,'model' => 'P', 'status' => 'Active'],
['make_id' => 76,'model' => 'YT30', 'status' => 'Active'],
['make_id' => 76,'model' => 'YT50', 'status' => 'Active'],
['make_id' => 76,'model' => 'YT60T', 'status' => 'Active'],
['make_id' => 77,'model' => 'ESPERANTE', 'status' => 'Active'],
['make_id' => 78,'model' => '270', 'status' => 'Active'],
['make_id' => 78,'model' => '320', 'status' => 'Active'],
['make_id' => 78,'model' => '330', 'status' => 'Active'],
['make_id' => 78,'model' => '357', 'status' => 'Active'],
['make_id' => 78,'model' => '362', 'status' => 'Active'],
['make_id' => 78,'model' => '377', 'status' => 'Active'],
['make_id' => 78,'model' => '378,', 'status' => 'Active'],
['make_id' => 78,'model' => '379', 'status' => 'Active'],
['make_id' => 78,'model' => '38,5', 'status' => 'Active'],
['make_id' => 78,'model' => '38,7', 'status' => 'Active'],
['make_id' => 79,'model' => '206', 'status' => 'Active'],
['make_id' => 79,'model' => '306', 'status' => 'Active'],
['make_id' => 79,'model' => '406', 'status' => 'Active'],
['make_id' => 80,'model' => 'NEON', 'status' => 'Active'],
['make_id' => 80, 'model' =>'PROWLER', 'status' => 'Active'],
['make_id' => 81,'model' => '120 XC SP', 'status' => 'Active'],


['make_id' => 115,'model' => 'F5', 'status' => 'Active'],
['make_id' => 43,'model' => 'Click w', 'status' => 'Active'],
['make_id' => 43,'model' => 'Getz', 'status' => 'Active'],
['make_id' => 43,'model' => 'Click m', 'status' => 'Active'],
['make_id' => 43,'model' => 'Vesto', 'status' => 'Active'],
['make_id' => 43,'model' => 'Atos', 'status' => 'Active'],
['make_id' => 43,'model' => 'Verna', 'status' => 'Active'],
['make_id' => 43,'model' => 'Terracan', 'status' => 'Active'],
['make_id' => 43,'model' => 'i10', 'status' => 'Active'],
['make_id' =>43,'model' => 'i20', 'status' => 'Active'],
['make_id' => 43,'model' => 'Tucson', 'status' => 'Active'],
['make_id' => 43,'model' => 'i10 Grand', 'status' => 'Active'],
['make_id' => 52,'model' => 'Picanto', 'status' => 'Active'],
['make_id' => 97,'model' => 'Yaris', 'status' => 'Active'],
['make_id' => 115,'model' => 'F3', 'status' => 'Active'],
['make_id' => 97,'model' => 'HILUX', 'status' => 'Active'],
['make_id' => 115,'model' => 'L3', 'status' => 'Active'],
['make_id' => 65,'model' => 'Attrage', 'status' => 'Active'],
['make_id' => 52,'model' => 'Picanto', 'status' => 'Active'],
['make_id' => 116,'model' => 'Fabia', 'status' => 'Active'],
['make_id' => 43,'model' => 'Atoz Prime', 'status' => 'Active'],
['make_id' => 97,'model' => 'Haice', 'status' => 'Active'],
['make_id' => 43,'model' => 'Grand Starex', 'status' => 'Active'],
['make_id' => 43,'model' => 'Accent Giad', 'status' => 'Active'],
['make_id' => 43,'model' => 'Lavita', 'status' => 'Active'],
['make_id' => 43,'model' => 'Avanti', 'status' => 'Active'],
['make_id' => 85,'model' => 'Duster', 'status' => 'Active'],
['make_id' => 65,'model' => 'Lancer', 'status' => 'Active'],
     ];


     VehicleModel::insert($data);
    }
}
